class Mappings {
  static var mappings = {
    'a': {
      '1': true,
      '2': false,
      '3': false,
      '4': false,
      '5': false,
      '6': false
    },
    'b': {'1': true, '2': true, '3': false, '4': false, '5': false, '6': false},
    'c': {'1': true, '2': false, '3': false, '4': true, '5': false, '6': false},
    'd': {'1': true, '2': false, '3': false, '4': true, '5': true, '6': false},
    'e': {'1': true, '2': false, '3': false, '4': false, '5': true, '6': false},
    'f': {'1': true, '2': true, '3': false, '4': true, '5': false, '6': false},
    'g': {'1': true, '2': true, '3': false, '4': true, '5': true, '6': false},
    'h': {'1': true, '2': true, '3': false, '4': false, '5': true, '6': false},
    'i': {'1': false, '2': true, '3': false, '4': true, '5': false, '6': false},
    'j': {'1': false, '2': true, '3': false, '4': true, '5': true, '6': false},
    'k': {'1': true, '2': false, '3': true, '4': false, '5': false, '6': false},
    'l': {'1': true, '2': true, '3': true, '4': false, '5': false, '6': false},
    'm': {'1': true, '2': false, '3': true, '4': true, '5': false, '6': false},
    'n': {'1': true, '2': false, '3': true, '4': true, '5': true, '6': false},
    'o': {'1': true, '2': false, '3': true, '4': false, '5': true, '6': false},
    'p': {'1': true, '2': true, '3': true, '4': true, '5': false, '6': false},
    'q': {'1': true, '2': true, '3': true, '4': true, '5': true, '6': false},
    'r': {'1': true, '2': true, '3': true, '4': false, '5': true, '6': false},
    's': {'1': false, '2': true, '3': true, '4': true, '5': false, '6': false},
    't': {'1': false, '2': true, '3': true, '4': true, '5': true, '6': false},
    'u': {'1': true, '2': false, '3': true, '4': false, '5': false, '6': true},
    'v': {'1': true, '2': true, '3': true, '4': false, '5': false, '6': true},
    'w': {'1': false, '2': true, '3': false, '4': true, '5': true, '6': true},
    'x': {'1': true, '2': false, '3': true, '4': true, '5': false, '6': true},
    'y': {'1': true, '2': false, '3': true, '4': true, '5': true, '6': true},
    'z': {'1': true, '2': false, '3': true, '4': false, '5': true, '6': true},
    '.': {'1': false, '2': true, '3': false, '4': false, '5': true, '6': true},
    ',': {
      '1': false,
      '2': true,
      '3': false,
      '4': false,
      '5': false,
      '6': false
    },
    ' ': {
      '1': false,
      '2': false,
      '3': false,
      '4': false,
      '5': false,
      '6': false
    }
  };

  static var gradeTwoMappings = {    
    'a': {'1': true, '2': false,'3': false,'4': false,'5': false,'6': false},
    'but': {'1': true, '2': true, '3': false, '4': false, '5': false, '6': false},
    'can': {'1': true, '2': false, '3': false, '4': true, '5': false, '6': false},
    'do': {'1': true, '2': false, '3': false, '4': true, '5': true, '6': false},
    'every': {'1': true, '2': false, '3': false, '4': false, '5': true, '6': false},
    'from': {'1': true, '2': true, '3': false, '4': true, '5': false, '6': false},
    'go': {'1': true, '2': true, '3': false, '4': true, '5': true, '6': false},
    'have': {'1': true, '2': true, '3': false, '4': false, '5': true, '6': false},
    'just': {'1': false, '2': true, '3': false, '4': true, '5': true, '6': false},
    'knowledge': {'1': true, '2': false, '3': true, '4': false, '5': false, '6': false},
    'like': {'1': true, '2': true, '3': true, '4': false, '5': false, '6': false},
    'more': {'1': true, '2': false, '3': true, '4': true, '5': false, '6': false},
    'not': {'1': true, '2': false, '3': true, '4': true, '5': true, '6': false},
    'people': {'1': true, '2': true, '3': true, '4': true, '5': false, '6': false},
    'quite': {'1': true, '2': true, '3': true, '4': true, '5': true, '6': false},
    'rather': {'1': true, '2': true, '3': true, '4': false, '5': true, '6': false},
    'so': {'1': false, '2': true, '3': true, '4': true, '5': false, '6': false},
    'that': {'1': false, '2': true, '3': true, '4': true, '5': true, '6': false},
    'us': {'1': true, '2': false, '3': true, '4': false, '5': false, '6': true},
    'very': {'1': true, '2': true, '3': true, '4': false, '5': false, '6': true},
    'will': {'1': false, '2': true, '3': false, '4': true, '5': true, '6': true},
    'it': {'1': true, '2': false, '3': true, '4': true, '5': false, '6': true},
    'you': {'1': true, '2': false, '3': true, '4': true, '5': true, '6': true},
    'as': {'1': true, '2': false, '3': true, '4': false, '5': true, '6': true},
    'and': {'1': true, '2': true, '3': true, '4': true, '5': false, '6': true},
    'for': {'1': true, '2': true, '3': true, '4': true, '5': true, '6': true},
    'of': {'1': true, '2': true, '3': true, '4': false, '5': true, '6': true},
    'the': {'1': false, '2': true, '3': true, '4': true, '5': false, '6': true},
    'with': {'1': false, '2': true, '3': true, '4': true, '5': true, '6': true},
    'child': {'1': true, '2': false, '3': false, '4': false, '5': false, '6': true},
    'ch': {'1': true, '2': false, '3': false, '4': false, '5': false, '6': true},
    'gh': {'1': true, '2': true, '3': false, '4': false, '5': false, '6': true},
    'shall': {'1': true, '2': false, '3': false, '4': true, '5': false, '6': true},
    'sh': {'1': true, '2': false, '3': false, '4': true, '5': false, '6': true},
    'this': {'1': true, '2': false, '3': false, '4': true, '5': true, '6': true},
    'th': {'1': true, '2': false, '3': false, '4': true, '5': true, '6': true},
    'which': {'1': true, '2': false, '3': false, '4': false, '5': true, '6': true},
    'wh': {'1': true, '2': false, '3': false, '4': false, '5': true, '6': true},
    'ed': {'1': true, '2': true, '3': false, '4': true, '5': false, '6': true},
    'er': {'1': true, '2': true, '3': false, '4': true, '5': true, '6': true},
    'out': {'1': true, '2': true, '3': false, '4': false, '5': true, '6': true},
    'ou': {'1': true, '2': true, '3': false, '4': false, '5': true, '6': true},
    'ow': {'1': false, '2': true, '3': false, '4': true, '5': false, '6': true},
    'bb': {'1': false, '2': true, '3': true, '4': false, '5': false, '6': false},
    'cc': {'1': false, '2': true, '3': false, '4': false, '5': true, '6': false},
    'dd': {'1': false, '2': true, '3': false, '4': false, '5': true, '6': true},
    'en': {'1': false, '2': true, '3': false, '4': false, '5': false, '6': true},
    'gg': {'1': false, '2': true, '3': true, '4': false, '5': true, '6': true},
    'were': {'1': false, '2': true, '3': true, '4': false, '5': true, '6': true},
    'in': {'1': false, '2': false, '3': true, '4': false, '5': true, '6': false},
    'st': {'1': false, '2': false, '3': true, '4': true, '5': false, '6': false},
    'ing': {'1': false, '2': false, '3': true, '4': true, '5': false, '6': true},
    'ar': {'1': false, '2': false, '3': true, '4': true, '5': true, '6': false}
    };

  static var brailleOutput = [];
  static int count = 0;
}
